services:
  web-npm:
    extends:
      file: ../src/web/docker-compose.yaml
      service: web-npm
  web-nginx:
    extends:
      file: ../src/web/docker-compose.yaml
      service: web-nginx

  web-game_server:
    extends:
      file: ../src/web/docker-compose.yaml
      service: web-game_server

  web-tournament_management:
    extends:
      file: ../src/web/docker-compose.yaml
      service: web-tournament_management

  web-user_management:
    extends:
      file: ../src/web/docker-compose.yaml
      service: web-user_management

  portainer:
    build: ../src/devops/portainer/.
    container_name: portainer
    ports:
      - "8001:8001"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data/portainer:/data
    environment:
      TZ: "Europe/Paris"
    # restart: on-failure
    networks:
      transcendence:
      
  postgres:
    image: postgres:13
    hostname: postgres_network
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "Europe/Paris"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    # restart: on-failure
    networks:
      transcendence:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  transcendence:
    driver: bridge
