services:
  vault:
    image: hashicorp/vault
    container_name: vault
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
      - VAULT_TOKEN=hvs.w4oPCidnWWdUPw4j5t6Gvazf
    volumes:
      - ../data/vault:/vault/data:z
      - ../devops/vault/config.hcl:/vault/config/config.hcl
    command: server 
    cap_add:
      - IPC_LOCK
    expose:
      - "8200:8200"
    networks:
      - gen_env

networks:
  gen_env: