services:  
  web-user_management:
    build:
      context: conf/UserManagement
      dockerfile: Dockerfile
    container_name: web-user_management
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8003"
    env_file:
      - ../../.env
    volumes:
      - ./conf/UserManagement/:/usr/src/app/logs/
      - ./conf/UserManagement/conf/:/usr/src/app/
    networks:
      transcendence:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/admin"]
      interval: 30s
      timeout: 10s
      retries: 5

  web-game_server:
    build:
      context: conf/GameServer
      dockerfile: Dockerfile
    container_name: web-game_server
    depends_on:
      web-user_management:
        condition: service_healthy
    ports:
      - "8001"
    env_file:
      - ../../.env
    volumes:
      - ./conf/GameServer/:/usr/src/app/logs/
      - ./conf/GameServer/conf/:/usr/src/app/
    networks:
      transcendence:

  web-npm:
    build:
      context: ./conf/Front
      dockerfile: Dockerfile_npm
    container_name: web-npm
    volumes:
      - ./conf/Front/npm/:/app
    ports:
      - "8080"
    environment:
      TZ: "Europe/Paris"
    env_file:
      - ../../.env
    depends_on:
      - web-game_server
    networks:
      - transcendence

  web-nginx:
    build:
      context: ./conf/Front
      dockerfile: Dockerfile_nginx
    container_name: web-nginx
    volumes:
      - ./conf/Front/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../data/logs/nginx/:/var/log/nginx/
      - ./conf/Front/nginx/certs:/etc/nginx/certs
      - ../../data/logs/modsecurity:/var/log/modsecurity/
      - ./conf/Front/npm/dist:/usr/share/nginx/html
    ports:
      - "443:443"
    environment:
      TZ: "Europe/Paris"
    depends_on:
      - web-npm
    networks:
      transcendence: